language: node_js
node_js:
  - "node"
before_script:
  - npm install -g uglify-es
script:
  - uglifyjs -m toplevel,eval -c -o public/dist/bundle.js public/js/src/FruitGame.js public/js/src/*.js
deploy:
  provider: firebase
  token:
    secure: "unhdjkRjJn0a9zQ/bRJJnBvGxAQiM27nBQqimMvpPnpz1ZndJPnVGYCYkEAIvsc/dBYiIATPKqkr4EDnGAohmcHR4X9NQStqPFV5wN1inkNycBSJLcGnlLZZXmVjG9b8DkLwq8/74kzANg4RNf5vdjM/PcEj78m+pmKLqiKmJqFrLJuHmZpc4fuEf7HZ5S3ZBBv6YKaNABD2vj295IcVK32eb6dCxZDLjoep5+pcph2OY8UaPyHb8vFYhNh5qXJDmIZXa3O14heq0cer7RFWa6CZWPbJYR2+y3nC/UXlVN2wmGWvXQgd/vXtjg53U+nc4E4jGcXgc6We36quQs3xT+TSg44aXA2QrMdLv7ke9BBTOVAy70kcPySp5yNP3WkvYFU14d1PSvADNcu5C2AtgPQkRy09ma/N1fZMsIOg79eVpJ4bp71uVq0sHGF5BYopH7eCXHoRrpvtSJo6bgkQCDv7nErCdF1xK6bEg3hTeuHB/dS8shA83dCX7lJv0YI7xF9MSFPXx+ipzlZcfUa6Hs9EGEiA3WEyer4u+AYkXV4LfH4xa3USklkpPMsEYBwc6PPGz7rZVN+m+K8TdwtHa0k2Cvgy+k49PVMyeMPRZLS7EINzKb7xmB/B85GKh2cpLvmuRIgqY3afBwf4Q7pQbLHGzx5Vfu2Tl1CYQtBRgIU="
