language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "b3OvxguXXK+TmZcvCFDkizii9nqh1F0fPr+bGN1ZvEDjxN51VMkG7PjXJnZ45Pw0gEZAR0KbmpSCM65jvq6JxwC/2EfYpXaGDupT6KkY8gZ8tEVDDhLJ85kg5BiyvWarkIM8+7qzptSycofqZ3BuUawsx0b5L6v0dJnoQ1BAcOEOXkv9hGRgMlCgXQwzMqADz1FsjTG2xYvV3YR82TFKjtFMicW6IfSEBnzYT425j1D/YrvYTcvdXgQdTCGnDEBdzzmhRqyssR52hYsCkp5CCdRtfD7iSkAIxd/CeaUg4hR83PtkWkx4twXY3cEQl2Sx2rfvRz7gOoDAYiuc7/1KedE3S7typ/OduUgWEMpLPQyJ77PNUzN6ZhXrdFdPWnfsuCFUwLtJ2+E5nZiRHWfuMQnt53y2ofDq0cICuVIdQHtnz9IKbStdiUhVwxox7H9qjwqwz/fuKxd2gD0QVT3Gje6bYSeGV05/G7vcCNp/j8fskB4hNt2QGp1N/mkgYOnnIy8OhW9DiLfar4T+73Qoq5XKep64Sbx0Lt2azY6mb2vAYXzNUSxXuAagO/zXKlmw7g+SsAH63oY6DirPmvyK32r1JpUoakjVTC3QNtq2SfgSK/hlwiw5M8Y7AAd1ZGt4FjGFIXKqDMty8O9gUWDVf6kvCjOYxPhc3KOBrGMzA7Q="